apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec: 
  containers:
    - name: nginx
      image: nginx 
      volumeMounts:
        - mountPath: "/var/www/htlm"
          name: mypd 
  volumes:
    - name: mypd 
      persistentVolumeClaim: 
        claimName: mypvc 