# dynamically creates storage 
apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
  name: azure-storage
provisioner: disk.csi.azure.com 
parameters:
  skuName: Premium_ZRS 
reclaimPolicy: Retain