apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx 
  namespace: default
  labels: 
    app: nginx 

spec: 
  selector: 
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels: 
        app: nginx 
    spec: 
      containers:
        - name: nginx-cont 
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits: 
              memory: 100Mi 
              cpu: 100m
          