apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - name: nginxc
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 50Mi
          cpu: 1 
        limits: 
          memory: 50Mi 
          cpu: 1 