apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: dashboard 
  namespace: default 


#After creaing service account, you need to create token with the same service account name
# kubectl create token dashboard
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  serviceAccount: dashboard
  containers:
    - name: nginxc
      image: nginx
      ports:
        - containerPort: 80