apiVersion: networking.k8s.io/v1 
kind: NetworkPolicy
metadata: 
  name: sample-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: sample 
  policyTypes:
  - Ingress 
  ingress:
  - from:
    - podSelector:
        matchLabels: 
          app: example 
    ports:
      - protocol: TCP 
        port: 3306 