apiVersion: v1 
kind: Service 
metadata: 
  name: example-service
spec:
  selector:
    app: example 
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80       # mandatory
      targetPort: 80 # target port is the port that this service forwards the requests to
      nodePort: 30008 # range for nodeports: 30000 - 32767
