apiVersion: v1
kind: Service
metadata:
  name: test-service 
  labels: 
    service: test 
spec:
  type: ClusterIP
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# Via a label selector, the client/user can identify a set of objects. The label selector is the core grouping primitive in Kubernetes.