apiVersion: v1 
kind: Pod 
metadata:
  name: ubuntu
  labels: 
    app: ubuntu 
spec: 
  containers:
    - name: ubuntu 
      image: ubuntu
      command:
        - "sleep" 
        - "1000"
      securityContext:
        runAsUser: 1001 
        capabilities:
          add: ["SYS_ADMIN","SYS_TIME"]